
import { GeminiFunctionDeclaration, GeminiType } from '../../../../types'; // Adjust path as necessary if types.ts is located elsewhere relative to this new file

export const outputGeneratedTextFunctionDeclaration: GeminiFunctionDeclaration = {
  name: 'output_generated_text',
  description: 'Outputs the generated text based on the user\'s prompt.',
  parameters: {
    type: GeminiType.OBJECT,
    properties: {
      generated_text: {
        type: GeminiType.STRING,
        description: 'The text content generated by the AI in response to the prompt.',
      },
    },
    required: ['generated_text'],
  },
};

export const EXPECTED_FUNCTION_ARG_NAME = 'generated_text';

// SYSTEM_INSTRUCTION_SUFFIX has been moved to AiTextGenerationNode's Definition.ts
